//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportCenter.Model
{
    using SportCenter.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class bookingInfo : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bookingInfo()
        {
            this.bills = new HashSet<bill>();
            this.buyingInfoes = new HashSet<buyingInfo>();
        }
        
        private int _id { get; set; }
        public int id { get => _id; set { _id = value; OnPropertyChanged(); } }

        private int _idField { get; set; }
        public int idField { get => _idField; set { _idField = value; OnPropertyChanged(); } }

        private DateTime _datePlay;
        public System.DateTime datePlay { get => _datePlay; set { _datePlay = value; OnPropertyChanged(); } }

        private DateTime _starttime { get; set; }
        public System.DateTime start_time { get => _starttime; set { _starttime = value;OnPropertyChanged(); } }

        private DateTime _endtime { get; set; }
        public System.DateTime end_time { get => _endtime; set { _endtime = value; OnPropertyChanged(); } }

        private string _status { get; set; }
        public string Status { get => _status; set { _status = value; OnPropertyChanged(); } }

        private string _cusName { get; set; }
        public string Customer_name { get => _cusName; set { _cusName = value;OnPropertyChanged(); } }

        private Nullable<int> _cusPhone { get; set; }
        public Nullable<int> Customer_PhoneNum { get => _cusPhone; set { _cusPhone = value; OnPropertyChanged(); } }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bill> bills { get; set; }
        public virtual field field { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<buyingInfo> buyingInfoes { get; set; }
    }
}
