//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportCenter.Model
{
    using SportCenter.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class employee : BaseViewModel
    {
        private int _id;
        public int id { get => _id; set { _id = value; OnPropertyChanged(); } }
        private string _name;
        public string name { get => _name; set { _name = value; OnPropertyChanged(); } }
        private Nullable<System.DateTime> _dateOfBirth;
        public Nullable<System.DateTime> dateOfBirth { get => _dateOfBirth; set { _dateOfBirth = value; OnPropertyChanged(); } }
        private string _role;
        public string role { get => _role; set { _role = value; OnPropertyChanged(); } }
        private Nullable<decimal> _salary;
        public Nullable<decimal> salary { get => _salary; set { _salary = value; OnPropertyChanged(); } }
        private string _phoneNumber;
        public string phoneNumber { get => _phoneNumber; set { _phoneNumber = value; OnPropertyChanged(); } }
        private byte[] _imageFile;
        public byte[] imageFile { get => _imageFile; set { _imageFile = value; OnPropertyChanged(); } }
    }
}
