//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportCenter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
        public string role { get; set; }
        public Nullable<decimal> salary { get; set; }
        public string phoneNumber { get; set; }
        public byte[] imageFile { get; set; }
    }
}
