//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportCenter.Model
{
    using SportCenter.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class good : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public good()
        {
            this.buyingInfoes = new HashSet<buyingInfo>();
        }

        private int _id;
        public int id { get => _id; set { _id = value; OnPropertyChanged(); } }

        private string _name;
        public string name { get => _name; set { _name = value; OnPropertyChanged(); } }

        private string _unit;
        public string unit { get => _unit; set { _unit = value; OnPropertyChanged(); } }

        private Nullable<Decimal> _price;
        public Nullable <Decimal> price
        { get => _price; set { _price = value; OnPropertyChanged(); } }

        private byte[] _imageFile;
        public byte[] imageFile { get => _imageFile; set { _imageFile = value; OnPropertyChanged(); } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<buyingInfo> buyingInfoes { get; set; }
    }
}
